---
- name: WEB install
  block:
    - name: Add nginx repo
      apt_repository: repo='ppa:nginx/stable'

    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Replace NGINX config
      copy:
        src: "templates/nginx.conf"
        dest: "/etc/nginx/nginx.conf"

  rescue:
    - name: Rollback changes if need
      command: date

